- hosts: all

  tasks:
  - name: ansible create directory with mode setting example
    file:
      path: /casestudy/createdirectoryAnsible/new
      state: directory
      owner:centosuser
      group:centosuser
      mode:0755

